openapi: 3.0.0
info:
  title: My BSC Image API
  description: API for managing images on the Binance Smart Chain
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /images/count:
    get:
      summary: Get the count of images
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: The count of images

  /images/{index}:
    get:
      summary: Get an image by index
      parameters:
        - in: path
          name: index
          required: true
          description: The index of the image
          schema:
            type: integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  image:
                    type: string
                    description: The image data

  /images:
    post:
      summary: Add a new image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ipfsHash:
                  type: string
                  description: The IPFS hash of the image
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  txHash:
                    type: string
                    description: The transaction hash of the added image

components:
  securitySchemes:
    BearerAuth:
      type: apiKey
      in: header
      name: Authorization
